version: '3.8'

services:

  app:
    build: .
    restart: always
    command: bash -c "sleep 5; python ./b2broker/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
